version: "3.9"

services:
    database:
        build: ./mariadb
        image: solarta-database
        container_name: solarta-database
        environment:
            - MARIADB_DATABASE=solarta
            - MARIADB_USER=solarta
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - api-db
        volumes:
            - db:/var/lib/mysql:rw
        read_only: true
        tmpfs:
            - /tmp
            - /run/mysqld
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges:true
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
                    pids: 1000
            restart_policy:
                condition: always
                delay: 3s

    api:
        build: ./backend
        image: solarta-api
        container_name: solarta-api
        environment:
            - SQLALCHEMY_DATABASE_URI=mysql+pymysql://solarta:${MARIADB_PASSWORD}@database:3306/solarta
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}
            - URL_SIGN_SECRET=${URL_SIGN_SECRET}
            - ONBOARDING_SALT=${ONBOARDING_SALT}
            - RESETTING_SALT=${RESETTING_SALT}
        networks:
            - api-db
            - proxy-api
        volumes:
            - /var/lib/solarta/assets/music:/assets/music:rw
        read_only: true
        tmpfs:
            - /tmp
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges:true
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
                    pids: 1000
            restart_policy:
                condition: always
                delay: 3s

    web:
        build: ./frontend
        image: solarta-web
        container_name: solarta-web
        networks:
            - proxy-web
        read_only: true
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges:true
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
                    pids: 1000
            restart_policy:
                condition: always
                delay: 1s

    proxy:
        build: ./nginx
        image: solarta-proxy
        container_name: solarta-proxy
        depends_on:
            - api
            - web
            - cicd
            - sast
        networks:
            - proxy-api
            - proxy-web
            - proxy-cicd
            - proxy-sast
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/log/nginx/api:/var/log/nginx/api:rw
            - /var/log/nginx/web:/var/log/nginx/web:rw
            - /var/log/nginx/jenkins:/var/log/nginx/jenkins:rw
            - /var/log/nginx/sonarqube:/var/log/nginx/sonarqube:rw
            - /etc/letsencrypt/live/solarta.nisokkususu.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            - /etc/letsencrypt/live/solarta.nisokkususu.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges:true
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 128M
                    pids: 500
            restart_policy:
                condition: always
                delay: 5s

    logger:
        image: gvalkov/tailon
        container_name: solarta-logger
        networks:
            - logger
        user: "1000:1000"
        command:
            - "/var/log/nginx/api/*.log"
            - "/var/log/nginx/web/*.log"
            - "/var/log/nginx/jenkins/*.log"
            - "/var/log/nginx/sonarqube/*.log"
        ports:
            - "127.0.0.1:8080:8080"
        volumes:
            - /var/log/nginx/api:/var/log/nginx/api:rw
            - /var/log/nginx/web:/var/log/nginx/web:rw
            - /var/log/nginx/jenkins:/var/log/nginx/jenkins:rw
            - /var/log/nginx/sonarqube:/var/log/nginx/sonarqube:rw
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 256M
                    pids: 1000
            restart_policy:
                condition: always
                delay: 1s

    cicd:
        build: ./jenkins
        image: solarta-cicd
        container_name: solarta-cicd
        environment:
            - JENKINS_OPTS=--prefix=/jenkins
        networks:
            - proxy-cicd
        volumes:
            - cicd:/var/jenkins_home:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 3G
                    pids: 1000
            restart_policy:
                condition: always
                delay: 1s

    sast:
        image: sonarqube
        container_name: solarta-sast
        environment:
            - SONAR_WEB_CONTEXT=/sonarqube
        networks:
            - proxy-sast
        volumes:
            - sast:/opt/sonarqube:rw
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 3G
                    pids: 1000
            restart_policy:
                condition: always
                delay: 1s

volumes:
    db:
        name: solarta-db-volume
        external: false
    cicd:
        name: solarta-cicd-volume
        external: false
    sast:
        name: solarta-sast-volume
        external: false

networks:
    api-db:
        name: solarta-api-db-local
        internal: true
    proxy-api:
        name: solarta-proxy-api-local
        internal: false
    proxy-web:
        name: solarta-proxy-web-local
        internal: true
    proxy-cicd:
        name: solarta-proxy-cicd-local
        internal: false
    proxy-sast:
        name: solarta-proxy-sast-local
        internal: false
    logger:
        name: solarta-logger-local
        internal: false
