version: "3.9"

services:
    database:
        build: ./mariadb
        image: solarta-database
        container_name: solarta-database
        environment:
            - MARIADB_DATABASE=solarta
            - MARIADB_USER=solarta
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - api-db
        volumes:
            - db:/var/lib/mysql
        cap_drop:
            - ALL
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
                    pids: 1000
            restart_policy:
                condition: always
                delay: 3s

    api:
        build: ./backend
        image: solarta-api
        container_name: solarta-api
        environment:
            - SQLALCHEMY_DATABASE_URI=mysql+pymysql://solarta:${MARIADB_PASSWORD}@database:3306/solarta
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}
            - URL_SIGN_SECRET=${URL_SIGN_SECRET}
            - ONBOARDING_SALT=${ONBOARDING_SALT}
            - RESETTING_SALT=${RESETTING_SALT}
            - WTF_CSRF_SECRET_KEY=${WTF_CSRF_SECRET_KEY}
        networks:
            - api-db
            - proxy-api
        volumes:
            - /var/lib/solarta/assets/music:/assets/music:rw
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
                    pids: 1000
            restart_policy:
                condition: always
                delay: 3s

    web:
        build: ./frontend
        image: solarta-web
        container_name: solarta-web
        networks:
            - proxy-web
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 1G
                    pids: 1000
            restart_policy:
                condition: always
                delay: 1s

    proxy:
        build: ./nginx
        image: solarta-proxy
        container_name: solarta-proxy
        depends_on:
            - api
            - web
            - cicd
        networks:
            - proxy-api
            - proxy-web
            - proxy-cicd
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt/live/solarta.nisokkususu.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            - /etc/letsencrypt/live/solarta.nisokkususu.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 256M
                    pids: 500
            restart_policy:
                condition: always
                delay: 5s

    cicd:
        build: ./jenkins
        image: solarta-cicd
        container_name: solarta-cicd
        environment:
            - JENKINS_OPTS=--prefix=/jenkins
        networks:
            - proxy-cicd
        volumes:
            - cicd:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 2G
                    pids: 1000
            restart_policy:
                condition: always
                delay: 1s

volumes:
    db:
        name: solarta-db-volume
        external: false
    cicd:
        name: solarta-cicd-volume
        external: false

networks:
    api-db:
        name: solarta-db-local
    proxy-api:
        name: solarta-proxy-api-local
    proxy-web:
        name: solarta-proxy-web-local
    proxy-cicd:
        name: solarta-proxy-cicd-local
